argo-cd:

  global:
    image:
      repository: argoproj/argocd
      tag: v1.8.7

  redis:
    enabled: true

#  dex:
#    image:
#      tag: v2.28.0

  server:
    ingress:
      enabled: true
      hosts:
        - "data-dev.lsst.eu"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      paths:
        - /argo-cd(/|$)(.*)

    extraArgs:
      - "--basehref=/argo-cd"
      - "--insecure=true"

    config:
      url: https://data-dev.lsst.eu/argo-cd
      dex.config: |
        connectors:
          # Auth using GitHub.
          # See https://dexidp.io/docs/connectors/github/
          - type: github
            id: github
            name: GitHub
            config:
              clientID: ae314e45a6af43ea910a
              # Reference to key in argo-secret Kubernetes resource
              clientSecret: $dex.clientSecret
              orgs:
                - name: rubin-in2p3
      helm.repositories: |
        - url: https://lsst-sqre.github.io/charts/
          name: lsst-sqre
        - url: https://ricoberger.github.io/helm-charts/
          name: ricoberger
        - url: https://kubernetes.github.io/ingress-nginx/
          name: ingress-nginx
        - url: https://charts.helm.sh/stable
          name: stable
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
           hs = {}
           hs.status = "Healthy"
           return hs 

    rbacConfig:
      policy.csv: |
        g, rubin-in2p3:admin, role:admin

  configs:
    secret:
      createSecret: true

vault_secret:
  enabled: true
  path: secret/k8s_operator/rsp-cc/argocd

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-cc/pull-secret
